name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: Log level
        required: true
        default: INFO
        type: choice
        options:
          - dev-qa
          - staging
          - production
      environment:
        description: Environment to run tests against
        type: environment
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zip tool
        run: sudo apt-get install -y zip

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: lambda update-function-code \
            --function-name arn:aws:lambda:${{ env.AWS_DEFAULT_REGION }}:${{ env['AWS_ACCOUNT_ID_' + github.event.inputs.environment] }}:function:lambda_function_name \
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets['AWS_ACCESS_KEY_ID_' + github.event.inputs.environment] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets['AWS_SECRET_ACCESS_KEY_' + github.event.inputs.environment] }}
          AWS_DEFAULT_REGION: ${{ secrets['AWS_DEFAULT_REGION_' + github.event.inputs.environment] }}