name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Select the environment to deploy to
        required: true
        default: dev-qa
        type: choice
        options:
          - dev-qa
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zip tool
        run: sudo apt-get install -y zip

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: lambda update-function-code \
            --function-name ${{ vars.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1