name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Select the environment to deploy to
        required: true
        default: dev-qa  # Set the default environment here
        type: choice
        options:
          - dev-qa
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zip tool
        run: sudo apt-get install -y zip

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: lambda update-function-code \
            --function-name arn:aws:lambda:${{ secrets['AWS_DEFAULT_REGION_DEV_QA'] }}:${{ secrets['AWS_ACCOUNT_ID_DEV_QA'] }}:function:${{ secrets['LAMBDA_FUNCTION_NAME_DEV_QA }} \
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets['AWS_ACCESS_KEY_ID_DEV_QA'] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets['AWS_SECRET_ACCESS_KEY_DEV_QA'] }}
          AWS_DEFAULT_REGION: ${{ secrets['AWS_DEFAULT_REGION_DEV_QA'] }}
